### PR TITLE
Uploaded Phishing project

### PR DESCRIPTION
**Pull request by LoadingUser3**

### CODE REVIEW

**Comment by vladislavglad** [comment]
Tutorial seems to work, however, there are many "File not Found" errors such as these:

[2020-05-23T19:43:29.309Z]  "GET /Checkmark.png" Error (404): "Not found"
[2020-05-23T19:43:29.310Z]  "GET /FishEx.png" Error (404): "Not found"
[2020-05-23T19:43:29.314Z]  "GET /Success.wav" Error (404): "Not found"
[2020-05-23T19:43:29.314Z]  "GET /Fail.wav" Error (404): "Not found"
[2020-05-23T19:43:29.316Z]  "GET /Emailscripts.js" Error (404): "Not found"
[2020-05-23T19:43:29.350Z]  "GET /EmailStyle.css" Error (404): "Not found"

Also, for some reason the actual module does not load when "encountering" enemy ...

**Comment by LoadingUser3** [comment]
Updated the code, realized I forgot to change script locations for the rest of the emails.

Let me know if there is any other issues.

**Comment by vladislavglad** [comment]
There are the following type of errors whenever you mouse over a highlighted text and click on it: 

**Emailscripts.js:85 Uncaught TypeError: Cannot set property 'display' of undefined
at successF (VM113 Emailscripts.js:85)
at HTMLDivElement.onclick (index.html:242)
successF @ Emailscripts.js:85
onclick @ index.html:242**

... and there is no way to exit out of the module (when encountering an enemy)

I attached chrome's console error logs if that helps:

[instructions-errors.log](https://github.com/vladislavglad/game-project/files/4678819/instructions-errors.log)

[module-errors.log](https://github.com/vladislavglad/game-project/files/4678820/module-errors.log)

**Comment by LoadingUser3** [comment]
Added a way to exit the module for each email

Fixed bug with emails showing that, the logs helped thank you!

Let me know if there are any other bugs (I think one only happens on my browser, which is that a previous prompt will show up in the next div)

**Pull request closed without merging**
